CREATE TABLE IF NOT EXISTS CANCIONES_ENTITY (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    artista VARCHAR(255) NOT NULL,
    genero VARCHAR(100) NOT NULL,
    duracion DECIMAL(4,2) NOT NULL
);
